### ISSUE TITLE
Frank Copula when parameter is negative

### ISSUE THREAD

**Issue by lidiamandre** [lrnv/Copulas.jl#50]
I was using this package for the first time as I need to simulate from some copulas in Julia rather than in R. The Frank copula is defined for all the real values but 0 but here it doesn't allow me to generate when my parameter is negative (and hence when I have negative dependence in the data), could this be fixed please, many thanks :)

A good addition to this package would be to have more Extreme Value copulas, such as the ones we can generate from the evd package in R

**Comment by lrnv** [comment]
Hey ! Thanks for reaching out ! 

Yes negatively correlated archimedean copulad is something I am currently working on, through the Williamson transforms. This will be fixed in the next few releases I still need to implement the right interface.

Regarding EV copulas, this is also on the radar and will be done in the near future. Do not hesitate to propose a PR on this subject BTW !

**Comment by lrnv** [comment]
@lidiamandre Regarding extreme values copulas, I would really like to get some too. Do you have a reference that we could follow while implementing them ? You could propose a PR if you want I'll help you with it

**Comment by lidiamandre** [comment]
> @lidiamandre Regarding extreme values copulas, I would really like to get some too. Do you have a reference that we could follow while implementing them ? You could propose a PR if you want I'll help you with it

@lrnv the vignette for the evd package in R is quite good for that actually, at least to get the CDFs. Under the bvevd function. Don't know more, sorry

**Comment by lrnv** [comment]
Hey @lidiamandre this should now be fixed in version 0.1.14 :) I finally implemented the full Williamson transformations shananigans: 

- You can now provide your own generator and the package can sample from the corresponding archimedean copula without any issues
- We can now sample e.g. the ClaytonCopula with *negative* dependence structure in *any* dimension, while if i recall correctly, R::copula only does it for d=2 :)
- The franck is now able to take any real parameter and works correctly. 

would you mind checking if the new versions meets your expectations ? Then we may close this issue. I'll open anotherone for the extreme values stuff.

**Comment by lrnv** [comment]
I'll closed this as resolved now, feel free to re-open if you think it is necessary
